### ISSUE TITLE
WebCLI tests will intermittently fail due to timeout

### ISSUE THREAD

**Issue by barrymcgee** [canonical/jaas-dashboard#1064]
On several PRs, I have the test suite fail even though I have changed any code related to the webCLI

Restarting the tests and running though again will usually resolve it.

It looks like the timeout needs to be increased or it should be refactored to use aysnc/await?

<img width="1178" alt="Screenshot 2021-06-23 at 11 29 28" src="https://user-images.githubusercontent.com/505570/123082088-92ab4900-d416-11eb-8288-28c4e52869c7.png">

**Comment by hatched** [comment]
Hmm yeah this is related to some missing `act` calls. I'll look into it.

**Comment by anthonydillon** [comment]
@hatched could you give this issue a priority to triage this issue please?

**Comment by hatched** [comment]
Oops missed that when I triaged it. Done.

**Comment by huwshimi** [comment]
This is still happening, the output looks like this:

```
Summary of all failing tests
FAIL src/components/WebCLI/WebCLI.test.tsx (6.737 s)
  ● WebCLI › WebCLI Output › displays messages recieved over the websocket

    expect(element).toHaveAttribute("style", "height: 300px;") // element.getAttribute("style") === "height: 300px;"

    Expected the element to have attribute:
      style="height: 300px;"
    Received:
      style="height: 1px;"

      259 |         expect(
      260 |           document.querySelector(".webcli__output-content")
    > 261 |         ).toHaveAttribute("style", "height: 300px;");
          |           ^
      262 |         act(() => {
      263 |           WS.clean();
      264 |         });

      at src/components/WebCLI/WebCLI.test.tsx:261:11

  ● WebCLI › WebCLI Output › displays messages recieved over the websocket

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      193 |
      194 |   describe("WebCLI Output", () => {
    > 195 |     it("displays messages recieved over the websocket", async () => {
          |     ^
      196 |       clobberConsoleError();
      197 |       // ..until it receives a 'done' message.
      198 |       const server = new WS("ws://localhost:[123](https://github.com/canonical/jaas-dashboard/actions/runs/4348704053/jobs/7597540251#step:6:124)4/model/abc123/commands", {

      at src/components/WebCLI/WebCLI.test.tsx:195:5
      at src/components/WebCLI/WebCLI.test.tsx:194:3
      at Object.<anonymous> (src/components/WebCLI/WebCLI.test.tsx:36:1)

  ● WebCLI › WebCLI Output › displays ansi colored content colored

    A mock server is already listening on this url

      270 |       clobberConsoleError();
      271 |       // ..until it receives a 'done' message.
    > 272 |       const server = new WS("ws://localhost:1234/model/abc123/commands", {
          |                      ^
      273 |         jsonProtocol: true,
      274 |       });
      275 |       await generateComponent({

      at new Server (node_modules/mock-socket/dist/mock-socket.js:[163](https://github.com/canonical/jaas-dashboard/actions/runs/4348704053/jobs/7597540251#step:6:164)5:13)
      at new WS (node_modules/jest-websocket-mock/lib/jest-websocket-mock.cjs.js:111:19)
      at Object.<anonymous> (src/components/WebCLI/WebCLI.test.tsx:272:22)


Test Suites: 1 failed, 62 passed, 63 total
Tests:       2 failed, 299 passed, 301 total
Snapshots:   7 passed, 7 total
Time:        97.104 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
